### ISSUE TITLE
Miss a test file named: value_column_test.cpp 

### ISSUE THREAD

**Issue by lojian** [hyrise/DYOD_WS1920#6]
In the sprint 1 doc, it mentions "value_column_test.cpp". But it is not found in the repository.
"""
Once you are done with this, you can enable the tests in value_column_test.cpp. Check that all tests pass before you continue.
"""

**Comment by Bensk1** [comment]
Good catch. This is a leftover from times when segments where called columns. The tests can be found in value_segment_test.cpp

**Comment by lojian** [comment]
got it, thank you!
